/* Generated with cbindgen:0.29.0 */

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * print "Hello from the shared library!"
 */
void hello_world(void);

/**
 * add two numbers and return the result
 */
intptr_t add(intptr_t a, intptr_t b);

/**
 * multiply two numbers and return the result
 */
intptr_t multiply(intptr_t a, intptr_t b);
